### PR TITLE
Added support to set a MailChimp object-wide timeout value

### PR DESCRIPTION
**Pull request by hvt**
A backwards compatible addition of an object-wide default timeout value.

### CODE REVIEW

**Comment by drewm** [comment]
I think this has already been superseded by a different commit with the same end functionality.

Thank you all the same.

**Comment by hvt** [comment]
Too bad that in that implementation, you must still provide the timeout for each individual call :].

**Comment by drewm** [comment]
I don't believe so - what am I missing?

**Comment by hvt** [comment]
If I want to change the timeout for all calls to, say 20 seconds, I have to include this value in each and every call (since `MailChimp::TIMEOUT` is a constant).

**Comment by drewm** [comment]
Hmm, I guess so.

What do you think about this? https://github.com/drewm/mailchimp-api/issues/180

**Comment by hvt** [comment]
That looks great :].

Thanks for letting me know about HTTPlug, I wasn't aware of it, looks great!

**Pull request closed without merging**
