### PR TITLE
Update project (fix/improve travis, improve PhpUnit and add CS-Fixer)

### PR DESCRIPTION
**Pull request by maxhelias**
I improved the unit tests for it to be done on different versions of php and more coverage.
I also added PHP-CS-Fixer to ckeck the coding style and I executed it.
I also added a new instance `MailChimpException`

I'm waiting for your comments, because I have other PR to submit that depends on it
Maxime

### CODE REVIEW

**Comment by drewm** [comment]
The readme states:

>  If you'd like to suggest an improvement, please raise an issue to discuss it before making your pull request.

Did we discuss these changes, because I don't recall doing so. What's the rationale for these proposed changes?

**Comment by maxhelias** [comment]
You're welcome 😉 

There is no issue for these changes, I decided myself to do a little update to fix travis and increase tests with new assertions and PHP-CS-Fixer.
And improving an open-source project that I like is a good reason, no?

**Comment by drewm** [comment]
Not when it's to try to steer it to your own preference and not consider the impact on others. What was the reason for cutting off PHP 5.3 users with your changes?

**Comment by maxhelias** [comment]
And it's still possible for them to use the tag associate with the compatible version to continue using it

**Comment by drewm** [comment]
I'd fully agree that people should use newer PHP. Of course. But this is just a tiny library that is used as a dependancy for dozens of other libraries, WordPress and other CMS and framework plugins. I could be easily convinced to raise the minimum PHP requirement for a solid technical reason that enabled us to improve what the library does, but if we don't have a reason make this break on PHP 5.3 installations then we shouldn't.

I'm open to switching from Travis to something better if that makes sense. That should be one PR.

I'm open to introducing custom exceptions _if_ we can do so without making non-composer installs impractical. That should be another PR.

I'm very much in favour of improving tests where we can. That should be another PR.

I'm not interested in raising the minimum requirements unless we have a solid technical reason.

Making all these changes in one PR, without discussing them first is just not good practice. I can't selectively accept parts of it so I'm going to have to sadly reject the entire thing. If you'd like to contribute, I'd very much welcome it and thank you for your effort, but it needs to be done properly.

**Comment by maxhelias** [comment]
Alright I understand. I'm going to take care of split all that then in several points

**Pull request closed without merging**
